name: Build Docker and Upload to Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        hbuilderx:
          - version: alpha
            url: https://download1.dcloud.net.cn/download/HBuilderX.4.84.2025102304-alpha.linux_x64.full.tar.gz
          - version: stable
            url: https://download1.dcloud.net.cn/download/HBuilderX.4.84.2025110307.linux_x64.full.tar.gz

    name: Build HBuilderX Docker Image (${{ matrix.hbuilderx.version }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for HBuilderX ${{ matrix.hbuilderx.version }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t hbuilderx:${{ matrix.hbuilderx.version }} \
            --build-arg HBUILDERX_URL=${{ matrix.hbuilderx.url }} \
            --output type=docker,dest=./hbuilderx.${{ matrix.hbuilderx.version }}.tar .

      - name: Build Slim Docker image for HBuilderX ${{ matrix.hbuilderx.version }}
        if: always()
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t hbuilderx:${{ matrix.hbuilderx.version }}-slim \
            --build-arg HBUILDERX_URL=${{ matrix.hbuilderx.url }} \
            --build-arg SLIM=true \
            --output type=docker,dest=./hbuilderx.${{ matrix.hbuilderx.version }}-slim.tar .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hbuilderx.${{ matrix.hbuilderx.version }}.tar.zip
          path: ./hbuilderx.${{ matrix.hbuilderx.version }}.tar

      - name: Upload slim artifact
        uses: actions/upload-artifact@v4
        with:
          name: hbuilderx.${{ matrix.hbuilderx.version }}-slim.tar.zip
          path: ./hbuilderx.${{ matrix.hbuilderx.version }}-slim.tar
          

  release:
    needs: build
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Download built image
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./hbuilderx.*.tar
          body: |
            ## HBuilderX Docker Images

            This release contains Docker images for HBuilderX.

            - hbuilderx.alpha.tar: Docker image for HBuilderX Alpha version
            - hbuilderx.stable.tar: Docker image for HBuilderX Stable version

            ### Usage

            To load the Docker image, use the following command:

            ```bash
            docker load -i hbuilderx.<version>.tar
            ```

            After loading the image, you can run the container using:
            
            ```bash
            docker run -it hbuilderx:<tag>
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
